# Minimize pause/resume
# yes: pause video when the window is minimized, resume after restore.
# no: keep video playing when the window is minimized.
pause_on_minimize=yes

# Delay values are in seconds. Usually no need to change them.
minimize_delay=0.2
resume_delay=0.5
