#设置 youtube 要获取的赞助片段的服务地址
#youtube_sponsor_server=https://sponsor.ajay.app/api/skipSegments
#设置 bilibili 要获取的赞助片段的服务地址
#bilibili_sponsor_server=https://bsbsb.top/api/skipSegments
#指定要获取和跳过的类别
#categories="sponsor"
#连接 SponsorBlock 服务的超时秒数
connect_timeout=5
#SponsorBlock 单次请求的总超时秒数
request_timeout=10
